---
name: Check for leaks
description: |
  Checks if any secrets were accidentally committed
inputs:
  github-access-token:
    description: GitHub access token (GITHUB_TOKEN)
    required: false

runs:
  using: composite
  steps:
    - name: Run gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github-access-token }}
        GITLEAKS_CONFIG: ${{ github.action_path }}/defaults/gitleaks.toml
        GITLEAKS_LICENSE: requested-key-multiple-times-but-got-no-reply-12345
        GITLEAKS_VERSION: latest
