---
name: Serverless Container Redeploy
description: Trigger a redeploy on a Serverless Container
inputs:
  vendor:
    description: The vendor to communicate with (azure, digitalocean, scaleway)
    required: true
  container-id:
    description: Target Scaleway Serverless container ID
    required: true
  # Vendor: Azure
  azure-client-id:
    description: Azure client ID for login with an Azure service principal
    required: false
  azure-tenant-id:
    description: Azure tenant ID for login with an Azure service principal
    required: false
  azure-subscription-id:
    description: Azure subscription ID for login with an Azure service principal
    required: false
  # Vendor: DigitalOcean
  digitalocean-api-token:
    description: DigitalOcean API token
    required: false
  # Vendor: Scaleway
  scaleway-organization-id:
    description: Scaleway organization ID
    required: false
  scaleway-project-id:
    description: Scaleway project ID
    required: false
  scaleway-region:
    description: Scaleway deployment region (such as nl-ams)
    required: false
  scaleway-access-key:
    description: Scaleway API key ID
    required: false
  scaleway-secret-key:
    description: Scaleway API key secret
    required: false

runs:
  using: composite
  steps:
    # Vendor setup
    - uses: wisemen-digital/devops-github-actions/.github/actions/infra/serverless-container/setup@v2
      with:
        vendor: ${{ inputs.vendor }}
        container-id: ${{ inputs.container-id }}
        # Vendor: azure
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}
        # Vendor: digitalocean
        digitalocean-api-token: ${{ inputs.digitalocean-api-token }}
        # Vendor: scaleway
        scaleway-organization-id: ${{ inputs.scaleway-organization-id }}
        scaleway-project-id: ${{ inputs.scaleway-project-id }}
        scaleway-region: ${{ inputs.scaleway-region }}
        scaleway-access-key: ${{ inputs.scaleway-access-key }}
        scaleway-secret-key: ${{ inputs.scaleway-secret-key }}

    - name: Trigger redeploy
      shell: bash
      run: |
        set -euo pipefail

        case "${{ inputs.vendor }}" in
          scaleway)
            scw container container redeploy "${{ inputs.container-id }}" region="${{ inputs.scaleway-region }}"
            ;;
          *)
            echo "Unsupported vendor '${{ inputs.vendor }}'"
            exit 1
            ;;
        esac
