---
name: Serverless Container Setup
description: Prepare tooling for communication with infra
inputs:
  vendor:
    description: The vendor to communicate with (azure, digitalocean, scaleway)
    required: true
  container-id:
    description: Target Scaleway Serverless container ID
    required: true
  # Vendor: Azure
  azure-client-id:
    description: Azure client ID for login with an Azure service principal
    required: false
  azure-tenant-id:
    description: Azure tenant ID for login with an Azure service principal
    required: false
  azure-subscription-id:
    description: Azure subscription ID for login with an Azure service principal
    required: false
  # Vendor: DigitalOcean
  digitalocean-api-token:
    description: DigitalOcean API token
    required: false
  # Vendor: Scaleway
  scaleway-organization-id:
    description: Scaleway organization ID
    required: false
  scaleway-project-id:
    description: Scaleway project ID
    required: false
  scaleway-region:
    description: Scaleway deployment region (such as nl-ams)
    required: false
  scaleway-access-key:
    description: Scaleway API key ID
    required: false
  scaleway-secret-key:
    description: Scaleway API key secret
    required: false

runs:
  using: composite
  steps:
    # Validate inputs (common setup validates the rest)
    - name: Validate inputs
      shell: bash
      run: |
        function validate-required-input {
          if [ -z "$2" ]; then echo "Missing input: $1"; exit 1; fi
        }

        echo "Validating inputs for vendor: ${{ inputs.vendor }}"
        case "${{ inputs.vendor }}" in
          azure)
            validate-required-input azure-resource-group '${{ inputs.azure-resource-group }}'
            ;;
          digitalocean)
            ;;
          scaleway)
            validate-required-input scaleway-region '${{ inputs.scaleway-region }}'
            ;;
          *)
            echo "Unsupported vendor '${{ inputs.vendor }}'"
            exit 1
            ;;
        esac

    # Vendor common setup
    - uses: wisemen-digital/devops-github-actions/.github/actions/infra/common/setup@v1
      with:
        vendor: ${{ inputs.vendor }}
        # Vendor: azure
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}
        # Vendor: digitalocean
        digitalocean-api-token: ${{ inputs.digitalocean-api-token }}
        # Vendor: scaleway
        scaleway-organization-id: ${{ inputs.scaleway-organization-id }}
        scaleway-project-id: ${{ inputs.scaleway-project-id }}
        scaleway-access-key: ${{ inputs.scaleway-access-key }}
        scaleway-secret-key: ${{ inputs.scaleway-secret-key }}
