---
name: Rollout database instance (Scaleway)

#
# Check what's changed (via filters, or provide your own list) and roll it out.
#

on:
  workflow_call:
    # Depends on the following vars
    # - SCALEWAY_REGION
    inputs:
      rdb-instance-deployments:
        description: List of rdb instances to roll out (folders), separated by commas
        required: false
        type: string
    secrets:
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: true
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: true

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: ubuntu-latest
    outputs:
      deployments: ${{ steps.changed-paths-filter.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: changed-paths-filter
        uses: wisemen-digital/devops-ga-changed-paths-filter@main
        with:
          filter-file: .github/db-rollout-filters.yaml
          changes-override: ${{ inputs.rdb-instance-deployments }}

  rollout-to-db:
    name: Rollout to db
    needs: [generate-matrix]
    strategy:
      matrix:
        deployment: ${{ fromJson(needs.generate-matrix.outputs.deployments) }}
    if: ${{ needs.generate-matrix.outputs.deployments != '[]' }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.deployment.environment }}
    steps:
      - name: Get config file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            db/${{ matrix.deployment.path }}
            k8s/environments
      - name: Setup SCW CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          version: v2.24.0
          access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
          default-project-id: ${{ vars.SCALEWAY_PROJECT_ID }}
          default-organization-id: ${{ vars.SCALEWAY_ORGANIZATION_ID }}
      - name: Create/update database instance
        run: |
          ENGINE=$(yq '.instance_configuration.engine' db/${{ matrix.deployment.path }}/config.yaml);
          IS_HA_CLUSTER=$(yq '.instance_configuration.is_ha_cluster' db/${{ matrix.deployment.path }}/config.yaml);
          NODE_TYPE=$(yq '.instance_configuration.node-type' db/${{ matrix.deployment.path }}/config.yaml);
          VOLUME_SIZE=$(yq '.instance_configuration.volume-size' db/${{ matrix.deployment.path }}/config.yaml);
          VOLUME_TYPE=$(yq '.instance_configuration.volume-type' db/${{ matrix.deployment.path }}/config.yaml);

          id=$(scw rdb instance list name='${{ matrix.deployment.path }}' -o json | jq -r '.[] | select(.name == "${{ matrix.deployment.path }}") | .id');
          if [ -z "$id" ]; then
            scw rdb instance create name=${{ matrix.deployment.path }} engine=$ENGINE user-name=admin is-ha-cluster="$IS_HA_CLUSTER" node-type=$NODE_TYPE volume-size=$VOLUME_SIZE volume-type=$VOLUME_TYPE --wait;
          else
            scw rdb instance upgrade $id node-type=$NODE_TYPE --wait || true;
            scw rdb instance upgrade $id volume-type=$VOLUME_TYPE --wait || true;
            scw rdb instance upgrade $id volume-size=$VOLUME_SIZE --wait || true;
            if $IS_HA_CLUSTER == true; then
              scw rdb instance upgrade $id enable-ha=true --wait || true;
            fi
          fi
      - name: Create databases and users/privileges if not exists
        run: |
          DATABASES=$(yq '.databases[]' db/${{ matrix.deployment.path }}/config.yaml);
          id=$(scw rdb instance list name='${{ matrix.deployment.path }}' -o json | jq -r '.[] | select(.name == "${{ matrix.deployment.path }}") | .id');

          for db in $DATABASES; do
            scw rdb database create instance-id=$id name=$db || true;
            scw rdb user create instance-id=$id name=$db is-admin=false || true;
            scw rdb privilege set instance-id=$id database-name=$db user-name=$db permission=all;
          done
      - name: Commit database url to env
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Change: Add database URL's"
          # commit_options: '--no-verify --signoff'
          file_pattern: '*.properties'
          repository: .
