---
name: Rollout to Scaleway

#
# Trigger a rollout restart of all given deployments.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      organization-id:
        description: Scaleway organization ID
        required: true
        type: string
      project-id:
        description: Scaleway project ID
        required: true
        type: string
      region:
        description: Target deployment region (such as nl-ams)
        required: true
        type: string
      cluster-id:
        description: Target cluster ID
        required: true
        type: string
      cluster-deployments:
        description: List of deployments to rollout
        required: true
        type: string
      cluster-namespace:
        description: Cluster namespace to rollout in
        required: true
        type: string
    secrets:
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: true
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: true

jobs:
  rollout:
    name: Rollout kubernetes namespace ${{ inputs.cluster-namespace }}
    runs-on: ubuntu-latest
    steps:
      - name: Install scw tool
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
          default-organization-id: ${{ inputs.organization-id }}
          default-project-id: ${{ inputs.project-id }}
          export-config: true
          save-config: true
      - name: Save Scaleway kubeconfig
        run: scw k8s kubeconfig install ${{ inputs.cluster-id }} region=${{ inputs.region }}
      - name: Restart deployments
        run: |
          for deployment in ${{ inputs.cluster-deployments }}; do
            kubectl rollout restart deployment $deployment -n ${{ inputs.cluster-namespace }}
          done
