---
name: Calculate source environment

#
# Calculate the "source" environment for a given target one. The default
# mapping can be overriden, and you can always provide your own "source".
# 
# Example: the "source" for the "staging" environment is "test".
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      target:
        description: Target environment
        type: string
        required: true
      source:
        description: Source (will calculate if empty)
        type: string
        required: false
      map:
        description: Environment map (JSON, fallback to default map)
        type: string
    outputs:
      source:
        description: Calculated source
        value: ${{ jobs.calculate.outputs.source }}
      target:
        description: Target (normalized)
        value: ${{ jobs.calculate.outputs.target }}

env:
  default-map: '{"development": "development", "test": "development", "staging": "test", "production": "staging"}'

jobs:
  calculate:
    name: Calculate source environment
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.data.outputs.source }}
      target: ${{ steps.data.outputs.target }}
    steps:
      - id: data
        run: |
          target=`echo ${{ inputs.target }} | tr '[:upper:]' '[:lower:]'`
          echo "target=$target" >> "$GITHUB_OUTPUT"

          if [ ! -z "${{ inputs.source }}" ]; then
            echo "source=${{ inputs.source }}" >> "$GITHUB_OUTPUT"
          else
            env_map='${{ inputs.map || env.default-map }}'
            source=`echo $env_map | jq -r ".$target"`

            if [ "$source" != "null" ]; then
              echo "source=$source" >> "$GITHUB_OUTPUT"
            else
              echo "Unable to calculate source for ${{ inputs.target }}." >> $GITHUB_STEP_SUMMARY
              exit 1
            fi
          fi
