---
name: Lint YAML & Dockerfile

#
# Validate all yaml files in a given path
#

on:
  workflow_call:
    inputs:
      yaml-paths:
        description: List of paths to verify (defaults to current directory)
        default: '.github'
        required: false
        type: string
      enable-docker-linting:
        description: Enable dockerfile linting
        default: true
        required: false
        type: boolean
      docker-lint-recursive:
        description: Lint dockerfiles in ALL folders
        default: false
        required: false
        type: boolean

jobs:
  yaml-lint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: wisemen-digital/devops-ga-lint-yaml@main

  docker-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    if: ${{ inputs.enable-docker-linting }}
    env:
      HADOLINT_RECURSIVE: ${{ inputs.docker-lint-recursive }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: ${{ inputs.docker-lint-recursive }}
