---
name: Deploy Node documentation to GitHub Pages

#
# Deploy node documentation to github pages.
#

on:
  workflow_call:
    inputs:
      dist-path:
        description: Path to build output
        type: string
        required: true
      node-runtime:
        description: Node Version (such as `node@24`)
        default: 'node@lts'
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
        install: false
          runtime: ${{ inputs.node-runtime }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --no-runtime
      - name: Build documentation
        run: pnpm docs:build
      - name: Store archive
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ inputs.dist-path }}
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
